name: Publish Storage API Drive non GMS Implementation

on:
  workflow_run:
    # We'll run this workflow when the Publish Storage API is completed
    workflows: [ Publish Storage API ]
    types:
      - completed
  workflow_dispatch:

jobs:
  publish:
    name: Release build and publish Storage API Drive non GMS implementation
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: adopt
          java-version: 11

      - name: Update local properties for secrets
        run: echo CLIENT_ID="CLIENT_ID_VALUE" > ./local.properties

        # Builds the release artifacts of the library
      - name: Release build
        run: ./gradlew :storage-api-drive-nongms:assembleRelease
      - name: Source jar
        run: ./gradlew androidSourcesJar

        # Runs upload, and then closes & releases the repository
      - name: Publish to MavenCentral
        if: ${{ vars.RELEASE_FLAG == 'true' }}
        run: ./gradlew :storage-api-drive-nongms:publishReleasePublicationToSonatypeRepository --max-workers 1 closeAndReleaseSonatypeStagingRepository
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}

      # Runs upload to the staging repository
      - name: Publish to Staging area
        if: ${{ vars.RELEASE_FLAG != 'true' }}
        run: ./gradlew :storage-api-drive-nongms:publishReleasePublicationToSonatypeRepository --max-workers 1
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
          SIGNING_KEY_ID: ${{ secrets.SIGNING_KEY_ID }}
          SIGNING_PASSWORD: ${{ secrets.SIGNING_PASSWORD }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SONATYPE_STAGING_PROFILE_ID: ${{ secrets.SONATYPE_STAGING_PROFILE_ID }}
